// Generated by https://quicktype.io

export interface RestPago {
    code:                number;
    payment_id:          string;
    payment_transaction: string;
    payment_status:      string;
    message?:            string;
}
export interface Respuesta{
        code: number;
        name: string;
        message: string;
        boleto_pdf?: string;
        type: string;
}
// Generated by https://quicktype.io

export interface RespuestaConfirmacion {
    SDTVentasPagosRespuesta: SDTVentasPagosRespuesta;
}

export interface SDTVentasPagosRespuesta {
    Success:    boolean;
    SuccessMsg: string;
}
